// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LeoCore.Data.Models;

public partial class PERSON_FORMATION
{
    public int ID { get; set; }

    public int CLIENT_ID { get; set; }

    public string SUBJECT { get; set; }

    public DateOnly DATUM_START { get; set; }

    public int? DURATION { get; set; }

    public byte[] CERTIFICATE { get; set; }

    public string TYPE_TRAINER { get; set; }

    public string NAME_TRAINER { get; set; }

    public string FOLLOWED_OR_TEACHED { get; set; }

    public string INTERN_OR_EXTERN { get; set; }
}