// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LeoCore.Data.Models;

public partial class QUESTIONNAIRE
{
    public int ID { get; set; }

    public string DESCRIPTION { get; set; }

    public string INFO { get; set; }

    public DateTime DATE_VALID_START { get; set; }

    public DateTime? DATE_VALID_END { get; set; }

    public string QUESTIONNAIREcol { get; set; }

    public virtual ICollection<PERSON_QUESTIONNAIRE> PERSON_QUESTIONNAIREs { get; set; } = new List<PERSON_QUESTIONNAIRE>();

    public virtual ICollection<QUESTIONNAIRE_QUESTION> QUESTIONNAIRE_QUESTIONs { get; set; } = new List<QUESTIONNAIRE_QUESTION>();

    public virtual ICollection<TRAINING_QUESTIONNNAIRE> TRAINING_QUESTIONNNAIREs { get; set; } = new List<TRAINING_QUESTIONNNAIRE>();
}