// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LeoCore.Data.Models;

/// <summary>
/// 		
/// </summary>
public partial class SPECIALISATION
{
    public int ID { get; set; }

    public string DESCRIPTION { get; set; }
}