// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LeoCore.Data.Models;

public partial class TRAINING_TRAINER
{
    public int ID { get; set; }

    public int TRAINING_ID { get; set; }

    public string MANDATORY { get; set; }

    public DateTime DATE_VALID_START { get; set; }

    public DateTime? DATE_VALID_END { get; set; }

    public string CLIENT_ID { get; set; }

    public int? TRAINER_ID { get; set; }

    public virtual TRAINING TRAINING { get; set; }
}