// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LeoCore.Data.Models;

public partial class TRAINING_QUESTIONNNAIRE
{
    public int ID { get; set; }

    public int TRAINING_ID { get; set; }

    public int QUESTIONNAIRE_ID { get; set; }

    public string INFO { get; set; }

    public DateOnly DATE_VALID_START { get; set; }

    public DateOnly? DATE_VALID_END { get; set; }

    public int? TIME_LIFESPAN { get; set; }

    public virtual QUESTIONNAIRE QUESTIONNAIRE { get; set; }

    public virtual TRAINING TRAINING { get; set; }
}