// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LeoCore.Data.Models;

public partial class USERCODE
{
    public string USERCODEID { get; set; }

    public string USERCODEGROUPID { get; set; }

    public string PARENTUSERCODEID { get; set; }

    public string PARENTUSERCODEGROUPID { get; set; }

    public string DESCRIPTION { get; set; }

    public string DEPENDENCYSET { get; set; }

    public int? SORTORDER { get; set; }

    public string REMARK { get; set; }

    public string SOFTDELETED { get; set; }

    public virtual USERCODEGROUP USERCODEGROUP { get; set; }
}