
namespace LEO.Common.Literals {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonLiterals {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonLiterals() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LEO.Common.Literals.CommonLiterals", typeof(CommonLiterals).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info over.
        /// </summary>
        public static string AboutPageTitle {
            get {
                return ResourceManager.GetString("AboutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toevoegen.
        /// </summary>
        public static string AddButtonDisplayName {
            get {
                return ResourceManager.GetString("AddButtonDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} administratie.
        /// </summary>
        public static string AdministrationPageTitle {
            get {
                return ResourceManager.GetString("AdministrationPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOS administatieve schadedossiers.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terug.
        /// </summary>
        public static string BackButtonDisplayName {
            get {
                return ResourceManager.GetString("BackButtonDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terug naar lijst.
        /// </summary>
        public static string BackToListButtonDisplayName {
            get {
                return ResourceManager.GetString("BackToListButtonDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beheer.
        /// </summary>
        public static string BeheerEntityDisplayName {
            get {
                return ResourceManager.GetString("BeheerEntityDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuleren.
        /// </summary>
        public static string CancelButtonDisplayName {
            get {
                return ResourceManager.GetString("CancelButtonDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} werd door andere gebruiker verwijderd in de databank.
        /// </summary>
        public static string ChildRowMissingErrorMessage {
            get {
                return ResourceManager.GetString("ChildRowMissingErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wissen.
        /// </summary>
        public static string ClearButtonDisplayName {
            get {
                return ResourceManager.GetString("ClearButtonDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afsluiten.
        /// </summary>
        public static string CloseButtonDisplayName {
            get {
                return ResourceManager.GetString("CloseButtonDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} werd door andere gebruiker gelijktijdig gewijzigd in databank.
        /// </summary>
        public static string ConcurrencyErrorMessage {
            get {
                return ResourceManager.GetString("ConcurrencyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} werd succesvol gekopieerd en is nu geopend..
        /// </summary>
        public static string CopySuccessfullInfoMessage {
            get {
                return ResourceManager.GetString("CopySuccessfullInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuw aanmaken.
        /// </summary>
        public static string CreateButtonDisplayName {
            get {
                return ResourceManager.GetString("CreateButtonDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kan deze WGK medewerker niet aanmaken/bewerken in deze databank. Omwille van {0}.
        /// </summary>
        public static string CreateFailurefulInfoMessage {
            get {
                return ResourceManager.GetString("CreateFailurefulInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} moet aangemaakt worden vooraleer rijen kunnen toegevoegd worden.
        /// </summary>
        public static string CreateParentFirstMessage {
            get {
                return ResourceManager.GetString("CreateParentFirstMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} succesvol aangemaakt in databank.
        /// </summary>
        public static string CreateSuccessfulInfoMessage {
            get {
                return ResourceManager.GetString("CreateSuccessfulInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard-meldingen.
        /// </summary>
        public static string DashboardNotificationsDisplayName {
            get {
                return ResourceManager.GetString("DashboardNotificationsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verwijderen.
        /// </summary>
        public static string DeleteButtonDisplayName {
            get {
                return ResourceManager.GetString("DeleteButtonDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bent u zeker dat u dit item wil verwijderen?.
        /// </summary>
        public static string DeleteConfirmationMessage {
            get {
                return ResourceManager.GetString("DeleteConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kan {0} niet verwijderen uit databank. Omwille van {1}.
        /// </summary>
        public static string DeleteFailurefulInfoMessage {
            get {
                return ResourceManager.GetString("DeleteFailurefulInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} succesvol verwijderd in databank.
        /// </summary>
        public static string DeleteSuccessfulInfoMessage {
            get {
                return ResourceManager.GetString("DeleteSuccessfulInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string DetailButtonDisplayName {
            get {
                return ResourceManager.GetString("DetailButtonDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} is reeds toegevoegd.
        /// </summary>
        public static string DuplicateChildRowErrorMessage {
            get {
                return ResourceManager.GetString("DuplicateChildRowErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bewerken.
        /// </summary>
        public static string EditButtonDisplayName {
            get {
                return ResourceManager.GetString("EditButtonDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaart.
        /// </summary>
        public static string GisButtonDisplayName {
            get {
                return ResourceManager.GetString("GisButtonDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string HelpDisplayName {
            get {
                return ResourceManager.GetString("HelpDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handleiding.
        /// </summary>
        public static string HelpPageTitle {
            get {
                return ResourceManager.GetString("HelpPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} zoeken.
        /// </summary>
        public static string IdentificationPageTitle {
            get {
                return ResourceManager.GetString("IdentificationPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wijzigingen zullen verloren gaan door deze pagina te verlaten zonder op te slaan..
        /// </summary>
        public static string LeavePageWarningMessage {
            get {
                return ResourceManager.GetString("LeavePageWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string LogDisplayName {
            get {
                return ResourceManager.GetString("LogDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} aanmaken.
        /// </summary>
        public static string MaintenancePageCreateTitle {
            get {
                return ResourceManager.GetString("MaintenancePageCreateTitle", resourceCulture);
            }
        }

        
        /// <summary>
        ///   Looks up a localized string similar to {0} verwijderen.
        /// </summary>
        public static string MaintenancePageDeleteTitle {
            get {
                return ResourceManager.GetString("MaintenancePageDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} beheren.
        /// </summary>
        public static string MaintenancePageEditTitle {
            get {
                return ResourceManager.GetString("MaintenancePageEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afdrukken.
        /// </summary>
        public static string MaintenancePagePrintTitle {
            get {
                return ResourceManager.GetString("MaintenancePagePrintTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} selecteren.
        /// </summary>
        public static string MaintenancePageSelectTitle {
            get {
                return ResourceManager.GetString("MaintenancePageSelectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} detail.
        /// </summary>
        public static string MaintenancePageViewTitle {
            get {
                return ResourceManager.GetString("MaintenancePageViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen item.
        /// </summary>
        public static string NoItemMessage {
            get {
                return ResourceManager.GetString("NoItemMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OKButtonDisplayName {
            get {
                return ResourceManager.GetString("OKButtonDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Openen.
        /// </summary>
        public static string OpenButtonDisplayName {
            get {
                return ResourceManager.GetString("OpenButtonDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PagingSearchCriteria.
        /// </summary>
        public static string PagingSearchCriteriaDisplayName {
            get {
                return ResourceManager.GetString("PagingSearchCriteriaDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afdrukken.
        /// </summary>
        public static string PrintButtonDisplayName {
            get {
                return ResourceManager.GetString("PrintButtonDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vernieuwen.
        /// </summary>
        public static string RefreshButtonDisplayName {
            get {
                return ResourceManager.GetString("RefreshButtonDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RowVersion.
        /// </summary>
        public static string RowVersionDisplayName {
            get {
                return ResourceManager.GetString("RowVersionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opslaan.
        /// </summary>
        public static string SaveButtonDisplayName {
            get {
                return ResourceManager.GetString("SaveButtonDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tussentijds opslaan.
        /// </summary>
        public static string SaveInBetweenButtonDisplayName {
            get {
                return ResourceManager.GetString("SaveInBetweenButtonDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoeken.
        /// </summary>
        public static string SearchButtonDisplayName {
            get {
                return ResourceManager.GetString("SearchButtonDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoekcriteria.
        /// </summary>
        public static string SearchCriteriaDisplayName {
            get {
                return ResourceManager.GetString("SearchCriteriaDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoekresultaten.
        /// </summary>
        public static string SearchResultsDisplayName {
            get {
                return ResourceManager.GetString("SearchResultsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andere selecteren.
        /// </summary>
        public static string SelectButtonDisplayName {
            get {
                return ResourceManager.GetString("SelectButtonDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is een onverwachte fout opgetreden.
        /// </summary>
        public static string UnexpectedErrorMessage {
            get {
                return ResourceManager.GetString("UnexpectedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bijwerken.
        /// </summary>
        public static string UpdateButtonDisplayName {
            get {
                return ResourceManager.GetString("UpdateButtonDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} succesvol bijgewerkt in databank.
        /// </summary>
        public static string UpdateSuccessfulInfoMessage {
            get {
                return ResourceManager.GetString("UpdateSuccessfulInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usercode.
        /// </summary>
        public static string UserCodeEntityDisplayName {
            get {
                return ResourceManager.GetString("UserCodeEntityDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usercodes succesvol herladen.
        /// </summary>
        public static string UserCodeReloadSuccessfulInfoMessage {
            get {
                return ResourceManager.GetString("UserCodeReloadSuccessfulInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is een fout opgetreden.
        /// </summary>
        public static string ValidationSummaryTitle {
            get {
                return ResourceManager.GetString("ValidationSummaryTitle", resourceCulture);
            }
        }
    }
}
