//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LEO.Common.Literals {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DossierLiterals {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DossierLiterals() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LEO.Common.Literals.DossierLiterals", typeof(DossierLiterals).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andere bewijsstukken.
        /// </summary>
        public static string BijlageAndereBewijsstukken {
            get {
                return ResourceManager.GetString("BijlageAndereBewijsstukken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto&apos;s.
        /// </summary>
        public static string BijlageFotos {
            get {
                return ResourceManager.GetString("BijlageFotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gegevens van percelen die schade hebben geleden.
        /// </summary>
        public static string BijlageGegevensPercelen {
            get {
                return ResourceManager.GetString("BijlageGegevensPercelen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificatieregister of -fiche landbouw.
        /// </summary>
        public static string BijlageIdentificatieRegisterLandbouw {
            get {
                return ResourceManager.GetString("BijlageIdentificatieRegisterLandbouw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liggingsplan met aangeduide percelen.
        /// </summary>
        public static string BijlageLiggingsplan {
            get {
                return ResourceManager.GetString("BijlageLiggingsplan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopie van pacht of huurovereenkomst.
        /// </summary>
        public static string BijlagePachtOfHuurovereenkomst {
            get {
                return ResourceManager.GetString("BijlagePachtOfHuurovereenkomst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopie verzamelaanvraag.
        /// </summary>
        public static string BijlageVerzamelaanvraag {
            get {
                return ResourceManager.GetString("BijlageVerzamelaanvraag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dieren afkomstig uit een gebied van een erkende terreinbeherende vereniging of van de Vlaamse overheid:.
        /// </summary>
        public static string DierenAfkomstigErkendGebied {
            get {
                return ResourceManager.GetString("DierenAfkomstigErkendGebied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opgelet! De schade moet vastgesteld worden binnen een termijn van 14 dagen nadat de schade veroorzaakt werd!.
        /// </summary>
        public static string DossierWildSchadeOorzaakdatumValidatie14dagen {
            get {
                return ResourceManager.GetString("DossierWildSchadeOorzaakdatumValidatie14dagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naam van het gebied:.
        /// </summary>
        public static string NaamGebied {
            get {
                return ResourceManager.GetString("NaamGebied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opmerkingen.
        /// </summary>
        public static string Opmerkingen {
            get {
                return ResourceManager.GetString("Opmerkingen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schadelijder is.
        /// </summary>
        public static string Schadelijder {
            get {
                return ResourceManager.GetString("Schadelijder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schade vastgesteld op.
        /// </summary>
        public static string SchadeVastgesteldOp {
            get {
                return ResourceManager.GetString("SchadeVastgesteldOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schade veroorzaakt door volgende soort(en):.
        /// </summary>
        public static string SchadeVeroorzaaktDoorSoorten {
            get {
                return ResourceManager.GetString("SchadeVeroorzaaktDoorSoorten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schade veroorzaakt op.
        /// </summary>
        public static string SchadeVeroorzaaktOp {
            get {
                return ResourceManager.GetString("SchadeVeroorzaaktOp", resourceCulture);
            }
        }
    }
}
